### ISSUE TITLE
Drop use of tenacity dependency

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/ansible-compat#12]
As we want to minimize dependencies introduced by this library we should avoid use of tenacity.

As part of the same change we should allow user of the library to use the library without being forced to use our hardcoded retry logic (make the retries optional).

@webknjaz suggested use of backoff or writing our own.

**Comment by webknjaz** [comment]
So I took a minute to look at both tenacity and backoff. And it looks like the former is better maintained. Even though I'm not used to it and like backoff's API better, I think it's reasonable to keep tenacity.

We could make it optional if necessary. An example of the rewrite would be:
```python
try:
    import tenacity
except ImportError:
    tenacity = None

def noop_dec(f):
    return f

retry = @tenacity.retry(...) if tenacity else noop_dec

@retry
def do_smth():
    ...
```

Alternatively, it could be:
```python
...

def do_smth():
    ...

if tenacity:
    do_smth = @tenacity.retry(...)(do_smth)
```

It's also possible to make a thin wrapper in the `_compat` module abstracting this away.

**Comment by ssbarnea** [comment]
Fixed on master, now is a soft depenendency.
