### ISSUE TITLE
Ensure exec() can be used in live move (tee?)

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/ansible-compat#40]
Once requirement for using exec() inside molecule is to be able to get real-time output from the executed command. That is because most molecule commands are running playbooks and the user wants to see which tasks are executed in real time.

For linter we have the other use-case where we do not want to show the output but we want to analyze the output (that is already covered with current implementation).

Molecule makes use of https://github.com/pycontribs/subprocess-tee/blob/main/src/subprocess_tee/__init__.py in order to do that but we could consider doing that ourselves and benefit from reducing the number of dependencies we have.

We can defer this feature for another release as for the moment molecule could continue to use subprocess-tee instead of using `Runtime.exec()` but longer term, we will need a solution, as it would prevent molecule from using execution environments if we do not to it.

**Comment by ssbarnea** [comment]
@webknjaz WDYT about this?

**Comment by webknjaz** [comment]
There should probably be a separate generator/method emitting the new lines.
